version: '3.1'

services:

  db:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - '${POSTGRES_PORT}:5432'

  server:
    depends_on:
      - db
    image: node:16
    build: .
    restart: always
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/home/node/app

  