version: '3.1'

services:

  db:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - ./db_data:/var/lib/postgresql/data

  server:
    depends_on:
      - db
    build: .
    restart: always
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/app

volumes:
  db_data: